// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Format from "rescript/lib/es6/format.js";
import * as Gml$Graph from "../src/gml.bs.js";
import * as Ex_Graph_Samples$Graph from "./Ex_Graph_Samples.bs.js";

function node(n) {
  return {
          hd: [
            "label",
            {
              TAG: /* String */2,
              _0: n
            }
          ],
          tl: /* [] */0
        };
}

function edge(param) {
  return /* [] */0;
}

var $$let = Ex_Graph_Samples$Graph.G.V;

var $$let$1 = Ex_Graph_Samples$Graph.G.E;

var partial_arg_V = {
  hash: $$let.hash,
  equal: $$let.equal,
  label: $$let.label
};

var partial_arg_E = {
  src: $$let$1.src,
  dst: $$let$1.dst,
  label: $$let$1.label
};

var partial_arg_iter_vertex = Ex_Graph_Samples$Graph.G.iter_vertex;

var partial_arg_iter_edges_e = Ex_Graph_Samples$Graph.G.iter_edges_e;

var partial_arg = {
  V: partial_arg_V,
  E: partial_arg_E,
  iter_vertex: partial_arg_iter_vertex,
  iter_edges_e: partial_arg_iter_edges_e
};

var partial_arg$1 = Gml$Graph.Print;

var GmlPrinter = (function (param) {
      return partial_arg$1(partial_arg, param);
    })({
      node: node,
      edge: edge
    });

Curry._2(GmlPrinter.print, Format.std_formatter, Ex_Graph_Samples$Graph.sample1);

export {
  
}
/* GmlPrinter Not a pure module */
