// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Format from "rescript/lib/es6/format.js";
import * as Graphviz$Graph from "../src/graphviz.bs.js";
import * as Ex_Graph_Samples$Graph from "./Ex_Graph_Samples.bs.js";

var E = Ex_Graph_Samples$Graph.G.E;

function vertex_name(v) {
  return Curry._1(Ex_Graph_Samples$Graph.G.V.label, v);
}

function graph_attributes(param) {
  return /* [] */0;
}

function default_vertex_attributes(param) {
  return /* [] */0;
}

function vertex_attributes(param) {
  return /* [] */0;
}

function default_edge_attributes(param) {
  return /* [] */0;
}

function edge_attributes(param) {
  return /* [] */0;
}

function get_subgraph(param) {
  
}

var Gv = Graphviz$Graph.Dot({
      V: {},
      E: {
        src: E.src,
        dst: E.dst
      },
      iter_vertex: Ex_Graph_Samples$Graph.G.iter_vertex,
      iter_edges_e: Ex_Graph_Samples$Graph.G.iter_edges_e,
      graph_attributes: graph_attributes,
      default_vertex_attributes: default_vertex_attributes,
      vertex_name: vertex_name,
      vertex_attributes: vertex_attributes,
      get_subgraph: get_subgraph,
      default_edge_attributes: default_edge_attributes,
      edge_attributes: edge_attributes
    });

Curry._2(Gv.fprint_graph, Format.str_formatter, Ex_Graph_Samples$Graph.sample1);

var s = Format.flush_str_formatter(undefined);

console.log(s);

export {
  
}
/* Gv Not a pure module */
