// Generated by ReScript, PLEASE EDIT WITH CARE


function pp_print_string(_state, _s) {
  
}

function print_string(_state, _s) {
  
}

function open_vbox(_state, _d) {
  
}

function read_line(param) {
  return "";
}

export {
  pp_print_string ,
  print_string ,
  open_vbox ,
  read_line ,
}
/* No side effect */
